### ISSUE TITLE
[QUESTION] Is it possible to run this code without AdGuard app?

### ISSUE THREAD

**Issue by MuhammadRestu999** [leohku/andure#1]
How to run it without installing AdGuard? :v

**Comment by MuhammadRestu999** [comment]
> You can try adding the included UserScript with TamperMonkey - though I don't have 100% confidence it will work since it hasn't been updated since 2013. [Google Play Link](https://play.google.com/store/apps/details?id=net.tampermonkey.dolphin)

It doesn't work on me

**Comment by leohku** [comment]
Unfortunate - it seems that installing AdGuard will be the only option to run `andure` for you. Alternatively, you can try installing [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&hl=en&gl=US), which has built-in desktop-class DevTools (though not all features are supported)

**Comment by porobertdev** [comment]
@MuhammadRestu999 @leohku 

Hey! I just tried this out using Bromite browser (without AdGuard or any other app), straight from its Settings > User Scripts. And it works! I attached 3 screenshots below.


**NOTE**: only the persistent version worked, at least on my Motorola G8 Power.

<details>
<summary>Screenshots</summary>
![Screenshot_20230503-110430_Bromite](https://user-images.githubusercontent.com/130125082/235862274-c7fdc277-3f3f-4888-9ad2-83195c691209.png)


![Screenshot_20230503-110435_Bromite](https://user-images.githubusercontent.com/130125082/235862284-854f0039-605a-42d7-99ca-7d8311cc29d9.png)
![Screenshot_20230503-110443_Bromite](https://user-images.githubusercontent.com/130125082/235862296-6e4eaf72-2f9c-480c-b2d7-2371b4ed9869.png)


![Screenshot_20230503-110443_Bromite](https://user-images.githubusercontent.com/130125082/235868863-a9b0e822-2949-4a9c-b551-148b5be4e782.png)

</details>

**Comment by leohku** [comment]
Oh! @porobertdev this is great news, thanks for letting me know. I'll reopen this issue so more people can know about this. I'll update the documentation to reflect this when I'm free. Thanks again!

**Comment by MuhammadRestu999** [comment]
*change the title so that other people looking for it can easily find it

**Comment by leohku** [comment]
@porobertdev A bit late, but the README is updated with credits - thanks!
